#!/usr/bin/env python3

from ads.cli import CliParser
from ads.cli.Actions import BootCommand

import os,argparse

dirpath = os.path.dirname(os.path.realpath(__file__))

epilog = """
---- Ansible Structure Assembler ---------------------------
"""

parser = argparse.ArgumentParser(
                    description='Generate Ansible directory structure',
                    epilog=epilog)

parser.add_argument('command', metavar='action:resource', type=str, nargs=1,
                    action=BootCommand,
                    help='action on a certain resource')

parser.add_argument('name', type=str, nargs='?',
                    default=None,
                    help='name for the resource')

parser.add_argument('--path', metavar='/curentPath', type=str, nargs='?',
                    default=None,
                    choices=['repo', 'inventory', 'roles'],
                    help='register the current path location')

parser.add_argument('--config', metavar='/configPath', type=str, nargs='?',
                    default=os.path.join(dirpath, "../config/ansible.yaml"),
                    help='register the path to the config file')

args = parser.parse_args()

cli = CliParser(path=os.getcwd(),
                config=args.config,
                action=args.command_action,
                resource=args.command_resource,
                name=args.name,
                path_module=args.path)

cli.runCommand()
