toplevel:
  config/:
    - ansible.cfg
  inventories/:
    - hosts
    - groups_vars/
    - hosts_vars/
  playbooks/: main.yaml
  roles/:
    tasks/: main.yaml
    handlers/: main.yaml
    files/: main.yaml
    templates/: main.yaml
    vars/: main.yaml
    defaults/: main.yaml
    meta/: main.yaml
